services:
  app:
    build: .
    image: killer-game:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/data/database.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    # Don't publish the app port publicly; Caddy will proxy to it.
    expose:
      - "3000"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:

